// Generated by CoffeeScript 1.4.0

$(function() {
  var log, menu, page, test_options;
  log = function() {
    return console.log.apply(console, arguments);
  };
  test_options = {
    data: {
      "current songs": ["this is a song", "not a song", "nice"],
      "history": ["ok", "old song by who", "someone like you", "dying", "in the sun", "rain"],
      "more": ["empty"]
    },
    callback: function(name) {
      var elem;
      elem = $("<div>");
      elem.text(name);
      return $("#out").append(elem);
    }
  };
  menu = new columnMenu(test_options);
  page = $("#page");
  return page.append(menu.menu);
});
